# Generated by Django 3.0.2 on 2021-02-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=255)),
                ('accion', models.CharField(max_length=255)),
                ('fecha_accion', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bitacora',
                'verbose_name_plural': 'Bitacora',
                'ordering': ['fecha_accion'],
            },
        ),
    ]
