# Generated by Django 3.0.2 on 2021-02-28 01:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_bitacora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Contenido',
                'verbose_name_plural': 'Contenidos',
                'ordering': ['id'],
            },
        ),
    ]
