# Generated by Django 4.0.4 on 2022-05-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='pregunta',
            field=models.CharField(blank=True, choices=[('Ciudad de nacimiento de tu madre?', 'Ciudad de nacimiento de tu madre?'), ('Profesión de tu abuelo?', 'Profesión de tu abuelo?'), ('Marca de coches favorita?', 'Marca de coches favorita?'), ('Nombre de tu mejor amigo?', 'Nombre de tu mejor amigo?'), ('Ciudad de nacimiento de tu padre?', 'Ciudad de nacimiento de tu padre?')], max_length=255, null=True, verbose_name='Pregunta de seguridad'),
        ),
    ]
