# Generated by Django 3.0.2 on 2021-02-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacorapersonal',
            name='fecha_entrada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bitacorapersonal',
            name='hora_entrada',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='bitacorapersonal',
            name='hora_salida',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
