# Generated by Django 3.0.2 on 2021-03-04 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20210224_2340'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BitacoraPersonal',
            new_name='RegistroDeAsistencia',
        ),
    ]
