# Generated by Django 3.0.2 on 2021-03-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20210303_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrodeasistencia',
            options={'ordering': ['hora_entrada'], 'verbose_name': 'Asistencia del Personal', 'verbose_name_plural': 'Asistencia del Personal'},
        ),
        migrations.AlterField(
            model_name='personal',
            name='cedula',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
